name: spectra
channels:
  - conda-forge
dependencies:
  - python==3.6.*
  - numpy==1.19.2
  - numba==0.49.1
  - scipy==1.2.1
  - sympy==1.6.1
  - jupyter
  - pip
  - pip:
    - matplotlib==3.3.2
    - PyQt5==5.12.3
    - pandas==1.1.2
    - beautifulsoup4==4.9.2
    - sqlalchemy==1.3.19
    - pyfiglet==0.8.post1
    - colorama==0.4.3
    - mendeleev==0.6.0
    - logzero==1.5.0
    - requests==2.24.0
